import streamlit as st
from PIL import Image
import json
from Classifier import KNearestNeighbours
from bs4 import BeautifulSoup
import requests,io
import PIL.Image
from urllib.request import urlopen

st.set_page_config(
   page_title="Bibliophile",
)

with open('book-rec.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

with open('../Data/book_data.json', 'r+', encoding='utf-8') as f:
    data = json.load(f)
with open('../Data/book_titles.json', 'r+', encoding='utf-8') as f:
    book_titles = json.load(f)


def book_Recommender(test_point, k):
    # Create dummy target variable for the KNN Classifier
    target = [0 for item in book_titles]
    # Instantiate object for the Classifier
    model = KNearestNeighbours(data, target, test_point, k=k)
    # Run the algorithm
    model.fit()
    # Print list of 10 recommendations < Change value of k for a different number >
    table = []
    for i in model.indices:
        # Returns back movie title and imdb link
        table.append([book_titles[i][0], book_titles[i][2], data[i][-1]])
    print(table)
    return table

def run():
    img1 = Image.open('../Images/logo.jpg')
    img1 = img1.resize((700,400),)
    st.image(img1,use_column_width=False)
    st.title("Bibliophile")
    genres = ['Madness at the Fair that Changed America',
 ' Absurdism',
 ' Absurdist fiction',
 ' Action fiction',
 ' Adventure',
 ' Adventure fiction',
 ' African-American literature',
 ' Allegory',
 ' Alternate history',
 ' Alternative universe',
 ' Animation',
 ' Anthology',
 ' Autobiographical Fiction',
 ' Autobiographical comics',
 ' Autobiographical novel',
 ' Autobiography',
 ' Bildungsroman',
 ' Biographical Fiction',
 ' Biography',
 ' Black comedy',
 ' Chick lit',
 " Children's literature",
 ' Christian Fiction',
 ' Christian apologetics',
 ' Christian literature',
 ' Comedy',
 ' Comedy horror',
 ' Comedy-drama',
 ' Comic fantasy',
 ' Comic science fiction',
 ' Coming-of-Age Fiction',
 ' Conspiracy fiction',
 ' Contemporary romance',
 ' Cookbook',
 ' Creative nonfiction',
 ' Crime',
 ' Crime Fiction',
 ' Cyberpunk',
 ' Cyberpunk derivatives',
 ' Dark fantasy',
 ' Decadent movement',
 ' Detective fiction',
 ' Diary fiction',
 ' Diet book',
 ' Domestic Fiction',
 ' Drama',
 ' Dystopia',
 ' Dystopian Fiction',
 ' Economics',
 ' Egyptian mythology',
 ' Encyclopedic novel',
 ' Entrepreneurship',
 ' Epic',
 ' Epistolary novel',
 ' Exhibition catalogue',
 ' Fable',
 ' Family saga',
 ' Fantastique',
 ' Fantasy',
 ' Fantasy Fiction',
 ' Fiction',
 ' Folklore',
 ' Ghost story',
 ' Gothic fiction',
 ' Graphic novel',
 ' Greek mythology',
 ' Guidebook',
 ' Harem',
 ' High fantasy',
 ' Historical Fiction',
 ' History',
 ' Horror fiction',
 ' Humorous Fiction',
 ' Humour',
 ' Inspirational Fiction',
 ' Investment',
 ' Juvenile fantasy',
 ' Legal Story',
 ' Legal thriller',
 ' Literary fiction',
 ' Magic',
 ' Magical Realism',
 ' Medical fiction',
 ' Memoir',
 ' Metafiction',
 ' Modern Literature',
 ' Morality play',
 ' Mystery',
 ' Mysticism',
 ' Nautical fiction',
 ' Noir fiction',
 ' Non-fiction',
 ' Non-fiction comics',
 ' Non-fiction novel',
 ' Novel',
 ' Novella',
 ' Occult Fiction',
 ' Paranoid fiction',
 ' Paranormal fiction',
 ' Paranormal romance',
 ' Philosophical fiction',
 ' Picaresque Fiction',
 ' Picture book',
 ' Poetry',
 ' Political fantasy',
 ' Political fiction',
 ' Political satire',
 ' Post-Apocalyptic fiction',
 ' Postmodern literature',
 ' Postmodernism',
 ' Psychological Fiction',
 ' Psychological horror',
 ' Psychological thriller',
 ' Psychology',
 ' Reference work',
 ' Romance',
 ' Romance Film',
 ' Romance nove',
 ' Romance novel',
 ' Saga',
 ' Satire',
 ' Sc,inavian noir',
 ' Science Fiction',
 ' Science fantasy',
 ' Self-help',
 ' Self-help book',
 ' Social commentary',
 ' Social novel',
 ' Social science fiction',
 ' Soft science fiction',
 ' Southern Gothic',
 ' Speculative fiction',
 ' Spirituality',
 ' Spy fiction',
 ' Steampunk',
 ' Superhero fiction',
 ' Supernatural fiction',
 ' Surrealism',
 ' Suspense',
 ' Techno-thriller',
 ' Thriller',
 ' Tragedy',
 ' Tragicomedy',
 ' Transgressive fiction',
 ' Travel literature',
 ' True crime',
 ' Urban fantasy',
 ' Utopian , dystopian fiction',
 ' Utopian fiction',
 ' Utopian fiction ',
 ' Vampire literature',
 ' War story',
 ' Western',
 ' Western fiction',
 ' Young adult fiction',
 ' dystopian fiction',
 ' historical fiction',
 '?Epic novel',
 'Adventure',
 'Adventure fiction',
 'African-American literature',
 'Alternate history',
 'Analysis',
 'Anthology',
 'Art',
 'Autobiographical novel',
 'Autobiography',
 'Beat Generation',
 'Bildungsroman',
 'Biographical Fiction',
 'Biography',
 'Biopunk',
 'Black comedy',
 'Chick lit',
 'Child',
 "Childern's novel",
 "Children's literature",
 "Children's poetry",
 'Christian Fiction',
 'Christian literature',
 'Comedy',
 'Comedy Novel',
 'Comic',
 'Comic science fiction',
 'Comics',
 'Coming-of-Age Fiction',
 'Conspiracy fiction',
 'Contemporary fantasy',
 'Crime Fiction',
 'Dark fantasy',
 'Detective',
 'Detective fiction',
 'Domestic Fiction',
 'Drama',
 'Dystopia',
 'Epic poetry',
 'Epistolary novel',
 'Erotic literature',
 'Erotic romance novel',
 'Essay',
 'Exhibition catalogue',
 'Fable',
 'Fairy Tale',
 'Fairy tale',
 'Family saga',
 'Fantasy',
 'Fantasy Fiction',
 'Fantasy fiction',
 'Farce',
 'Fiction',
 'First-person shooter',
 'Gonzo journalism',
 'Gothic',
 'Gothic Fiction',
 'Gothic Novel',
 'Gothic fiction',
 'Graphic Novel',
 'Greek Mythology',
 'Hard science fiction',
 'Hardboiled',
 'Heroic fantasy',
 'High Fantasy',
 'High fantasy',
 'Historical Fiction',
 'Historical Novel',
 'Historical romance',
 'History',
 'Horror',
 'Horror Fiction',
 'Horror fiction',
 'Humor',
 'Humorous Fiction',
 'Humour',
 'Inspirational Fiction',
 'Juvenile fantasy',
 'Legal thriller',
 'LitRPG',
 'Literary fiction',
 'Literary realism',
 'Magical Realism',
 'Manga',
 'Medical history',
 'Memoir',
 'Milatary science fiction',
 'Misery lit',
 'Modern Literature',
 'Musical Theatre',
 'Mystery',
 'Mythopoeia',
 'Naturalism',
 'Non-Fiction',
 'Non-fiction',
 'Non-fiction novel',
 'Novel',
 'Novella',
 'Paranormal Fiction',
 'Paranormal fiction',
 'Paranormal romance',
 'Parnormal romance',
 'Personal finance',
 'Philosophical fiction',
 'Picaresque Fiction',
 'Picture book',
 'Poetry',
 'Popular science',
 'Post-Apocalyptic fiction',
 'Prose poetry',
 'Psychological Horror',
 'Psychological horror',
 'Psychological thriller',
 'Psychology',
 'Quest',
 'Religious text',
 'Romance',
 'Romance Film',
 'Romance novel',
 'Romantic',
 'Romantic comedy',
 'Romanticism',
 'Satire',
 'Science Fiction',
 'Self-help',
 'Self-help book',
 'Short story',
 'Short story collection',
 'Soft Science Fiction',
 'Southern Gothic',
 'Speculative fiction',
 'Spirituality',
 'Superhero',
 'Supernatural fiction',
 'Suspense',
 'Techno-thriller',
 'The Devil in the White City: Murder',
 'The Holocaust',
 'Thriller',
 'Tragedy',
 'Transgressive fiction',
 'Treatise',
 'True crime',
 'Tudor Series',
 'Urban fantasy',
 'Utopian',
 'Utopian , dystopian fiction',
 'Utopian dystopian fiction',
 'War',
 'War story',
 'Western',
 'Young Adult',
 'Young Adult Fiction',
 'Young adult',
 'Young adult Fiction',
 'Young adult fiction',
 'Young adult novel',
 'emoir',
 'iction',
 'romance',
 'vampire',
 'witchcraft',
 '�Fantasy',
 '�Fantasy Fiction',
 '�Fiction',
 '�Non-fiction',
 '�Poetry']
    authors = [' A.W. Wheen',
 ' Abraham Verghese',
 ' Adolph Caso',
 ' Akira Watanabe',
 ' Alan R. Clarke',
 ' Albus Dumbledore',
 ' Alethea Nibley',
 ' Alex Haley',
 ' Alexander Teixeira de Mattos',
 ' Alfred MacAdam',
 ' Alison Anderson',
 ' Andrew Delbanco',
 ' Angelo  Rinaldi',
 ' Anita Jeram',
 ' Anne Perry',
 ' Annie Barrows',
 ' Anonymous',
 ' Anthea Bell',
 ' Anthony Bonner',
 ' Arthur C. Clarke',
 ' Athena Nibley',
 ' Aylmer Maude',
 ' B.M. Mooyaart-Doubleday',
 ' Barbara A. Mowat',
 ' Benjamin Martinez',
 ' Bernard Knox',
 ' Bernie Wrightson',
 ' Beverly Cleary',
 ' Brett Helquist',
 ' Brian Bolland',
 ' Brian W. Aldiss',
 ' Cao Chi',
 ' Carlo Pagetti',
 ' Carol Brown Janeway',
 ' Carol Christensen',
 ' Catherine Belsey',
 ' Celâl Üster',
 ' Chris Sheban',
 ' Chris Tomlin',
 ' Christina Lamb',
 ' Christopher Bigsby',
 ' Christopher Hitchens',
 ' Christopher Tolkien',
 ' Claire Lamont',
 ' Clement Hurd',
 ' Craig Raine',
 ' Dan Chaon',
 ' Danae Yankoski',
 ' Dave Gibbons',
 ' Dave McKean',
 ' David   Lloyd',
 ' David J. Skal',
 ' David Levithan',
 ' David Mazzucchelli',
 ' David McDuff',
 ' David Oliver Relin',
 ' David Wenzel',
 ' Deidre Shauna Lynch',
 " Dennis O'Neil",
 ' Desmond Lee',
 ' Diana Burgin',
 ' Dom Marcos Barbosa',
 ' Douglas Smith',
 ' E.V. Rieu',
 ' Earl Lee',
 ' Edith Grossman',
 ' Edwin Muir',
 ' Eleanor Roosevelt',
 ' Elizabeth Sherrill',
 ' Ellen Forney',
 ' Ellendea Proffer',
 ' Eric Carle',
 ' Eric Lindor Fall',
 ' Erich Fromm',
 ' Ernest H. Shepard',
 ' Felicia Bond',
 ' Fiona Stafford',
 ' Florence Lamborn',
 ' Frédéric Mugler',
 ' G.B. Trudeau',
 ' Gail Kern Paster',
 ' Garth Williams',
 ' George Cruikshank',
 ' Gerald McCann',
 ' Gillian Avery',
 ' Giovanni Pontiero',
 ' Greg Bear',
 ' Gregory Rabassa',
 ' Guy Cardwell',
 ' Hablot Knight Browne',
 ' Henning Koch',
 ' Henry Gifford',
 ' Hilda Rosner',
 ' J.E. Thomas',
 ' J.K. Rowling',
 ' J.R.R. Tolkien',
 ' Jack Thorne',
 ' James Kinsley',
 ' James Stern',
 ' Jay Rubin',
 ' Jeffrey Eugenides',
 ' Jeffrey Zaslow',
 ' Jeremy Tambling',
 ' Jerry B. Jenkins',
 ' John Archambault',
 ' John D. MacDonald',
 ' John E. Woods',
 ' John Higgins',
 ' John Rutherford',
 ' John Seelye',
 ' John Sherrill',
 ' John Tenniel',
 ' Josef Scharl',
 ' Joseph Campbell',
 ' Jules Feiffer',
 ' Karen  Berger',
 " Katherine Tiernan O'Connor",
 ' Kathleen DeGrave',
 ' Kathryn Sutherland',
 ' Katy Bridges',
 ' Kenneth H. Blanchard',
 ' Klaus Janson',
 ' Kristin Cast',
 ' Lane Smith',
 ' Larissa Volokhonsky',
 ' Lauren Child',
 ' Lee Fahnestock',
 ' Leo Tolstoj',
 ' Leonard Peikoff',
 ' Lewis Carroll',
 ' Lois Ehlert',
 ' Louis Sachar',
 ' Louise Maude',
 ' Lucia Graves',
 ' Lynn Varley',
 ' Lynn Vincent',
 ' Magda Bogin',
 ' Malcolm Bowie',
 ' Malcolm Jones III',
 ' Margaret Jull Costa',
 ' Margaret Mauldon',
 ' Margaret R. Higonnet',
 ' Margaret Raine Hunt',
 ' Margaret Stohl',
 ' Marie Milpois',
 ' Marion Wiesel',
 ' Mark Overstall',
 ' Martin Gardner',
 ' Mary GrandPré',
 ' Matthew    Ward',
 ' Mattias Ripa',
 ' Maureen Howard',
 ' Maurice Hindle',
 ' Max Brod',
 ' Melina Karakosta',
 ' Mervyn Peake',
 ' Michael Glencross',
 ' Michael Hague',
 ' Michael Henry Heim',
 ' Michael Mason',
 ' Mike Dringenberg',
 ' Nancy Bond',
 ' Nancy Seligsohn',
 ' Ned Dameron',
 ' Neil Gaiman',
 ' Nell Scovell',
 ' Nevill Coghill',
 ' Nicola Kraus',
 ' Nina Auerbach',
 ' Nina Baym',
 ' Norman MacAfee',
 ' Padraic Colum',
 ' Paul Werstine',
 ' Paulette Møller',
 ' Pauline Baynes',
 ' Percy Bysshe Shelley',
 ' Peter Bart',
 ' Philip Gabriel',
 ' Philip Horne',
 ' Phạm Văn Thiều',
 ' Quentin Blake',
 ' Ralph Manheim',
 ' Ralph Steadman',
 ' Ray Cruz',
 ' Reg Keeland',
 ' Rene Cloke',
 ' Rex Gibson',
 ' Richard Andrews',
 ' Richard Howard',
 ' Richard J. Dunn',
 ' Richard Maxwell',
 ' Richard Pevear',
 ' Richmond Lewis',
 ' Robert           Jackson',
 ' Robert          Jackson',
 ' Robert DeMaria Jr.',
 ' Robert Fagles',
 ' Robert Thompson',
 ' Roberto González Echevarría',
 ' Robin Buss',
 ' Rod Bradbury',
 ' Roger Zelazny',
 ' Roma Gill',
 ' Ros Ballaster',
 ' Rosemary Wells',
 ' Roswitha Quadflieg',
 ' Rufus Beck',
 ' Rufus Goodwin',
 ' Russell Munson',
 ' Sally Beauman',
 ' Sam Kieth',
 ' Saulius Dagys',
 ' Seamus Heaney',
 ' Sean Deming',
 ' Seán Barrett',
 ' Sheila McGraw',
 ' Stanley Corngold',
 ' Stephen J. Dubner',
 ' Stephen King',
 ' Stuart Gilbert',
 ' Suzanne Toren',
 ' Takeshi Obata',
 ' Ted Nasmith',
 ' Thomas  Christensen',
 ' Thomas Cleary',
 ' Thomas E. Connolly',
 ' Tim Dolin',
 ' Tim Sale',
 ' Todd Klein',
 ' Tom Quirk',
 ' Tony Goldwyn',
 ' Tony Moore',
 ' Tony Tanner',
 ' Virginia Woolf',
 ' Vladimir Nabokov',
 ' W.W. Denslow',
 ' Walker Percy',
 ' Walter J. Cobb',
 ' Wilhelm Grimm',
 ' Willa Muir',
 ' William   Nicholson',
 ' William Olivier Desmond',
 ' William Shakespeare',
 ' William Weaver',
 ' Ροζίτα Σώκου',
 ' לאה נאור',
 'A.A. Milne',
 'Abbi Glines',
 'Abraham Verghese',
 'Agatha Christie',
 'Alan Moore',
 'Albert Camus',
 'Aldous Huxley',
 'Alex Flinn',
 'Alex Haley',
 'Alexander McCall Smith',
 'Alexandre Dumas',
 'Alice Sebold',
 'Alice Walker',
 'Allie Brosh',
 'Ally Carter',
 'Ally Condie',
 'Alyson Noel',
 'Amy Poehler',
 'Amy Tan',
 'Andre Dubus III',
 'Andy Weir',
 'Anita Diamant',
 'Ann Brashares',
 'Ann Patchett',
 'Anna Sewell',
 'Anne Frank',
 'Anne Rice',
 'Anonymous',
 'Anthony Bourdain',
 'Anthony Burgess',
 'Anthony Doerr',
 'Antoine de Saint-Exupéry',
 'Aravind Adiga',
 'Art Spiegelman',
 'Arthur C. Clarke',
 'Arthur Conan Doyle',
 'Arthur Golden',
 'Arthur Miller',
 'Arundhati Roy',
 'Astrid Lindgren',
 'Audrey Niffenegger',
 'Augusten Burroughs',
 'Ayn Rand',
 'Banksy',
 'Barack Obama',
 'Barbara Ehrenreich',
 'Barbara Kingsolver',
 'Beatrice Sparks',
 'Beatrix Potter',
 'Becca Fitzpatrick',
 'Bernhard Schlink',
 'Betty  Smith',
 'Betty Edwards',
 'Bill Bryson',
 'Bill Martin Jr.',
 'Bill Watterson',
 'Billie Letts',
 'Bisco Hatori',
 'Bram Stoker',
 'Brandon Sanderson',
 'Brent Weeks',
 'Bret Easton Ellis',
 'Brian Selznick',
 "Bryan Lee O'Malley",
 'C.S. Lewis',
 'Carlos Ruiz Zafón',
 'Cassandra Clare',
 'Cecelia Ahern',
 'Celeste Ng',
 'Charlaine Harris',
 'Charles Dickens',
 'Charles Duhigg',
 'Charles Frazier',
 'Charlotte Brontë',
 'Chelsea Handler',
 'Cheryl Strayed',
 'Chimamanda Ngozi Adichie',
 'Chinua Achebe',
 'Chris Bohjalian',
 'Chris Cleave',
 'Chris Van Allsburg',
 'Christina Baker Kline',
 'Christopher McDougall',
 'Christopher Moore',
 'Christopher Paolini',
 'Chuck Dixon',
 'Chuck Palahniuk',
 'Colleen Hoover',
 'Colleen McCullough',
 'Cormac McCarthy',
 'Cornelia Funke',
 'Corrie ten Boom',
 'Crockett Johnson',
 'Dale Carnegie',
 'Dan Brown',
 'Dan Simmons',
 'Daniel Defoe',
 'Daniel James Brown',
 'Daniel Kahneman',
 'Daniel Keyes',
 'Daphne du Maurier',
 'Dave Eggers',
 'Dave Pelzer',
 'David Guterson',
 'David Levithan',
 'David McCullough',
 'David Mitchell',
 'David Nicholls',
 'David Sedaris',
 'Dean Koontz',
 'Deborah Harkness',
 'Dennis Lehane',
 'Diana Gabaldon',
 'Diana Wynne Jones',
 'Diane Setterfield',
 'Don Freeman',
 'Donna Tartt',
 'Doris Kearns Goodwin',
 'Douglas Adams',
 'Dr. Seuss',
 'E. Lockhart',
 'E.B. White',
 'E.H. Gombrich',
 'E.L. James',
 'E.L. Konigsburg',
 'E.M. Forster',
 'Eckhart Tolle',
 'Edgar Allan Poe',
 'Edith Wharton',
 'Elie Wiesel',
 'Elizabeth Gilbert',
 'Elizabeth Kostova',
 'Ellen Raskin',
 'Emily Brontë',
 'Emily Giffin',
 'Emily St. John Mandel',
 'Emma Donoghue',
 'Emma McLaughlin',
 'Eoin Colfer',
 'Eric Carle',
 'Eric Schlosser',
 'Erich Maria Remarque',
 'Erik Larson',
 'Erin Morgenstern',
 'Ernest Cline',
 'Ernest Hemingway',
 'F. Scott Fitzgerald',
 'Fannie Flagg',
 'Frances Hodgson Burnett',
 'Frances Mayes',
 'Francine Rivers',
 'Francis Chan',
 'Frank Herbert',
 'Frank McCourt',
 'Frank Miller',
 'Franz Kafka',
 'Fredrik Backman',
 'Fyodor Dostoyevsky',
 'Gabriel García Márquez',
 'Gabrielle Zevin',
 'Gail Carson Levine',
 'Garth Nix',
 'Garth Stein',
 'Gary Chapman',
 'Gary Paulsen',
 'Gaston Leroux',
 'Gayle Forman',
 'Geoffrey Chaucer',
 'George Orwell',
 'George R.R. Martin',
 'Gillian Flynn',
 'Graeme Simsion',
 'Greg Mortenson',
 'Gregory David Roberts',
 'Gregory Maguire',
 'Gustave Flaubert',
 'H.A. Rey',
 'H.G. Wells',
 'Harper Lee',
 'Harriet Beecher Stowe',
 'Haruki Murakami',
 'Helen Fielding',
 'Helen Keller',
 'Henry David Thoreau',
 'Herman Melville',
 'Hermann Hesse',
 'Hilary Mantel',
 'Hiromu Arakawa',
 'Homer',
 'Howard Zinn',
 'Hugh Howey',
 'Hunter S. Thompson',
 'Ian McEwan',
 'Irvine Welsh',
 'Isaac Asimov',
 'Isabel Allende',
 'Ishmael Beah',
 'J.D. Robb',
 'J.D. Salinger',
 'J.K. Rowling',
 'J.M. Barrie',
 'J.R. Ward',
 'J.R.R. Tolkien',
 'Jack Kerouac',
 'Jack London',
 'Jacob Grimm',
 'Jacquelyn Mitchard',
 'James Clavell',
 'James Dashner',
 'James Frey',
 'James Patterson',
 'Jamie Ford',
 'Jamie McGuire',
 'Jane Austen',
 'Jane Carruth',
 'Jane Green',
 'Janet Evanovich',
 'Janet Fitch',
 'Jared Diamond',
 'Jay Asher',
 'Jean M. Auel',
 'Jeanne DuPrau',
 'Jeannette Walls',
 'Jeff Kinney',
 'Jeff Lindsay',
 'Jeffery Deaver',
 'Jeffrey Eugenides',
 'Jennifer Egan',
 'Jennifer L. Armentrout',
 'Jennifer Weiner',
 'Jenny  Lawson',
 'Jenny Han',
 'Jerry Spinelli',
 'Jess Walter',
 'Jhumpa Lahiri',
 'Jim Butcher',
 'Joan Didion',
 'Jodi Picoult',
 'Johanna Spyri',
 'John Berendt',
 'John Berger',
 'John Boyne',
 'John Gray',
 'John Green',
 'John Grisham',
 'John Grogan',
 'John Irving',
 'John Kennedy Toole',
 'John Knowles',
 'John Steinbeck',
 'John Tiffany',
 'Jojo Moyes',
 'Jon Krakauer',
 'Jon Scieszka',
 'Jonas Jonasson',
 'Jonathan Franzen',
 'Jonathan Safran Foer',
 'Jonathan Swift',
 'Jonathan Tropper',
 'Joseph Conrad',
 'Joseph Heller',
 'Jostein Gaarder',
 'José Saramago',
 'Judith Viorst',
 'Judy Blume',
 'Jules Verne',
 'Julian Barnes',
 'Julie Kagawa',
 'Julie Powell',
 'Junot Díaz',
 'Justin Cronin',
 'Justin Halpern',
 'Kahlil Gibran',
 'Kami Garcia',
 'Kate Atkinson',
 'Kate Chopin',
 'Kate DiCamillo',
 'Kate Egan',
 'Kate Morton',
 'Katherine Paterson',
 'Kathleen Grissom',
 'Kathryn Stockett',
 'Kazuo Ishiguro',
 'Kelley Armstrong',
 'Ken Follett',
 'Ken Kesey',
 'Kenneth Branagh',
 'Kenneth Grahame',
 'Khaled Hosseini',
 'Kiera Cass',
 'Kim Edwards',
 'Kody Keplinger',
 'Kristin Cashore',
 'Kristin Hannah',
 'Kurt Vonnegut Jr.',
 'L. Frank Baum',
 'L.M. Montgomery',
 'Laini Taylor',
 'Larry McMurtry',
 'Laura Esquivel',
 'Laura Hillenbrand',
 'Laura Ingalls Wilder',
 'Laura Joffe Numeroff',
 'Lauren Kate',
 'Lauren Oliver',
 'Lauren Weisberger',
 'Laurie Halse Anderson',
 'Lee Child',
 'Lemony Snicket',
 'Leo Tolstoy',
 'Lev Grossman',
 'Lewis Carroll',
 'Liane Moriarty',
 'Libba Bray',
 'Lionel Shriver',
 'Lisa Genova',
 'Lisa See',
 'Lois Lowry',
 'Louis Sachar',
 'Louisa May Alcott',
 'Louise Rennison',
 'Ludwig Bemelmans',
 'M.L. Stedman',
 'M.R. Carey',
 "Madeleine L'Engle",
 'Maggie Stiefvater',
 'Malala Yousafzai',
 'Malcolm Gladwell',
 'Malcolm X',
 'Margaret Atwood',
 'Margaret Mitchell',
 'Margaret Wise Brown',
 'Margery Williams Bianco',
 'Maria Semple',
 'Marie Lu',
 'Mario Puzo',
 'Marion Zimmer Bradley',
 'Marissa Meyer',
 'Marjane Satrapi',
 'Mark Cotta Vaz',
 'Mark Haddon',
 'Mark Twain',
 'Markus Zusak',
 'Mary Ann Shaffer',
 'Mary Kubica',
 'Mary Roach',
 'Mary Wollstonecraft Shelley',
 'Masashi Kishimoto',
 'Matthew Quick',
 'Maurice Sendak',
 'Max Brooks',
 'Maya Angelou',
 'Meg Cabot',
 'Melissa Bank',
 'Melissa Marr',
 'Michael  Grant',
 'Michael Chabon',
 'Michael Connelly',
 'Michael Crichton',
 'Michael Ende',
 'Michael Pollan',
 'Miguel Ruiz',
 'Miguel de Cervantes Saavedra',
 'Mikhail Bulgakov',
 'Milan Kundera',
 'Mindy Kaling',
 'Mitch Albom',
 'Muriel Barbery',
 'Napoleon Hill',
 'Natalie Babbitt',
 'Nathaniel Hawthorne',
 'Natsuki Takaya',
 'Neal Shusterman',
 'Neal Stephenson',
 'Ned Vizzini',
 'Neil Gaiman',
 'Newt Scamander',
 'Niccolò Machiavelli',
 'Nicholas Sparks',
 'Nick Hornby',
 'Nicole Krauss',
 'Norton Juster',
 'Oliver Sacks',
 'Orson Scott Card',
 'Oscar Wilde',
 'P.C. Cast',
 'P.D. Eastman',
 'Pat Conroy',
 'Patricia Cornwell',
 'Patrick Rothfuss',
 'Patrick Süskind',
 'Patti Smith',
 'Paul Kalanithi',
 'Paula Hawkins',
 'Paula McLain',
 'Paulo Coelho',
 'Pearl S. Buck',
 'Peter Benchley',
 'Phaidon Press',
 'Philip K. Dick',
 'Philip Pullman',
 'Philippa Gregory',
 'Pierce Brown',
 'Piper Kerman',
 'Pittacus Lore',
 'Plato',
 'R.J. Palacio',
 'Rachel Joyce',
 'Raina Telgemeier',
 'Rainbow Rowell',
 'Ralph Ellison',
 'Randy Pausch',
 'Ransom Riggs',
 'Ray Bradbury',
 'Rebecca Skloot',
 'Rebecca Wells',
 'Rhonda Byrne',
 'Richard Adams',
 'Richard Bach',
 'Richard Bachman',
 'Richard Dawkins',
 'Richelle Mead',
 'Rick Riordan',
 'Rick Warren',
 'Rick Yancey',
 'Roald Dahl',
 'Robert A. Heinlein',
 "Robert C. O'Brien",
 'Robert Galbraith',
 'Robert Jordan',
 'Robert Kirkman',
 'Robert Louis Stevenson',
 'Robert Ludlum',
 'Robert M. Pirsig',
 'Robert Munsch',
 'Robert T. Kiyosaki',
 'Robin Hobb',
 'Robin Sloan',
 'Rohinton Mistry',
 'S.E. Hinton',
 'S.J. Watson',
 'Sam McBratney',
 'Samantha Young',
 'Sara Gruen',
 'Sara Shepard',
 'Sarah Dessen',
 'Sarah J. Maas',
 'Scott Lynch',
 "Scott O'Dell",
 'Scott Westerfeld',
 'Seth Grahame-Smith',
 'Sharon Creech',
 'Shel Silverstein',
 'Sherman Alexie',
 'Sheryl Sandberg',
 'Simone Elkeles',
 'Sophie Kinsella',
 'Sophocles',
 'Spencer Johnson',
 'Stephanie Perkins',
 'Stephen Chbosky',
 'Stephen Hawking',
 'Stephen King',
 'Stephen R. Covey',
 'Stephenie Meyer',
 'Steven D. Levitt',
 'Stieg Larsson',
 'Sue Grafton',
 'Sue Monk Kidd',
 'Sun Tzu',
 'Susan Cain',
 'Susanna Clarke',
 'Susanna Kaysen',
 'Susannah Cahalan',
 'Suzanne Collins',
 'Sylvia Day',
 'Sylvia Nasar',
 'Sylvia Plath',
 'Tahereh Mafi',
 'Tammara Webber',
 'Tana French',
 'Tatiana de Rosnay',
 'Tennessee Williams',
 'Terry Goodkind',
 'Terry Pratchett',
 'Thomas Hardy',
 'Thomas Harris',
 'Thomas Keneally',
 'Tim LaHaye',
 "Tim O'Brien",
 'Tina Fey',
 'Tite Kubo',
 'Todd Burpo',
 'Tom Clancy',
 'Toni Morrison',
 'Tracy Chevalier',
 'Truman Capote',
 'Tsugumi Ohba',
 'Umberto Eco',
 'Unknown',
 'Upton Sinclair',
 'Ursula K. Le Guin',
 'V.C. Andrews',
 'Vanessa Diffenbaugh',
 'Veronica Roth',
 'Victor Hugo',
 'Victoria Aveyard',
 'Viktor E. Frankl',
 'Virginia Woolf',
 'Vladimir Nabokov',
 'Voltaire',
 'Wally Lamb',
 'Walter Isaacson',
 'William Faulkner',
 'William Gibson',
 'William Golding',
 'William Goldman',
 'William Landay',
 'William Paul Young',
 'William Peter Blatty',
 'William Shakespeare',
 'Wilson Rawls',
 'Yann Martel', 'Zora Neale Hurston']
    books = [title[0] for title in book_titles]
    st.markdown(f"**:red[Choose a Book Title]**")
    sel_book = st.selectbox('Select book: (Recommendation will be based on this selection)', ['--Select--'] + books)
    if sel_book == '--Select--':
        st.warning('Please select a Book!!')
    else:
        no_of_reco = st.slider('Number of books you want Recommended:', min_value=5, max_value=10, step=1)
        genres = data[books.index(sel_book)]
        test_points = genres
        table = book_Recommender(test_points, no_of_reco+1)
        table.pop(0)
        c = 0
        st.success('Some of the books from our Recommendation, have a look below')
        for book, author, publication_year in table:
            c+=1
            st.markdown(f"({c})Book Title -  **:green[{book}]**   \n Author - **:blue[{author}]**   \n Publication Year - **:red[{int(publication_year)}]**")

run()